### ISSUE TITLE
Adding an option for perl = TRUE

### ISSUE THREAD

**Issue by ProfFancyPants** [petermeissner/stringb#15]
I would like to suggest an enhancement that adds the ability for all the stringb functions to assume all patterns are written with perl style syntax. I love the regex features inside of stringr, and I would move to using stringb if I could keep using the same regex syntax conveniently.

**Comment by petermeissner** [comment]
That will not happen ...

The explicit core aim of the package:https://github.com/petermeissner/stringb/blob/master/README.md , is to provide regular expression that work the exact same way as base R regular expressions work and that is: not like in Perl.

That being said, base R string functions do have a `perl=FALSE` parameter. Stringb wraps around base R functions and aims at allowing to use all available base R parameters as well. See `?grep` for some documentation on the `perl` parameter. Therefore, you can switch to perl-mode via using `perl=TRUE` with stringb functions. 

example:

``` r
library(stringb)

text_replace("super-duper", "(.*-)(.*)", "\\1\\U\\2", perl = FALSE)
## [1] "super-Uduper"

text_replace("super-duper", "(.*-)(.*)", "\\1\\U\\2", perl = TRUE)
## [1] "super-DUPER"
```
